<?php
require_once __DIR__ . '/includes/auth.php';
if (isLoggedIn()) redirect(appUrl('dashboard.php'));
$error=''; $success=''; $referral=(string)($_GET['ref'] ?? '');
if ($_SERVER['REQUEST_METHOD']==='POST') {
    if (!verifyCsrf($_POST['csrf_token'] ?? null)) $error='Your session expired. Please try again.';
    else { $password=(string)post('password'); $confirm=(string)post('confirm_password'); if(strlen($password)<6) $error='Password must be at least 6 characters.'; elseif($password!==$confirm) $error='Passwords do not match.'; else { $result=registerUser((string)post('name'),(string)post('username'),(string)post('email'),(string)post('phone'),$password,(string)post('referral_code')); if($result['success']) $success='Registration complete. You can now sign in.'; else $error=$result['message']; } }
}
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Register - <?= e(APP_NAME) ?></title><link rel="stylesheet" href="assets/css/style.css"><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css"></head><body class="auth-page"><main class="auth-card wide"><div class="auth-logo"><span class="brand-mark">GM</span></div><h1>Create your account</h1><p class="muted">A safe demo workspace for testing the platform.</p><?php if($error): ?><div class="alert error"><?= e($error) ?></div><?php endif; ?><?php if($success): ?><div class="alert success"><?= e($success) ?> <a href="login.php">Sign in</a></div><?php endif; ?><form method="post" class="form-stack"><?= csrfField() ?><label>Full name<input name="name" required maxlength="100"></label><div class="form-grid"><label>Username<input name="username" pattern="[A-Za-z0-9_]{3,50}" required></label><label>Email<input type="email" name="email" required></label></div><div class="form-grid"><label>Phone<input name="phone" maxlength="20"></label><label>Referral code<input name="referral_code" value="<?= e($referral) ?>" maxlength="20"></label></div><div class="form-grid"><label>Password<input type="password" name="password" minlength="6" required></label><label>Confirm password<input type="password" name="confirm_password" minlength="6" required></label></div><button class="btn primary full" type="submit">Create account</button></form><p class="auth-switch">Already registered? <a href="login.php">Sign in</a></p></main></body></html>
