<?php
declare(strict_types=1); require_once __DIR__.'/../config/database.php';
function e($v):string{return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');} function money($v):string{return 'PKR '.number_format((float)$v,0);} function go(string $u):never{header('Location: '.$u);exit;}
function csrf():string{if(empty($_SESSION['csrf']))$_SESSION['csrf']=bin2hex(random_bytes(32));return $_SESSION['csrf'];} function check_csrf():void{if(!hash_equals($_SESSION['csrf']??'',$_POST['csrf']??'')){http_response_code(419);exit('Invalid CSRF token.');}}
function flash(string $t,string $m):void{$_SESSION['flash'][]=['type'=>$t,'message'=>$m];} function flashes():array{$x=$_SESSION['flash']??[];unset($_SESSION['flash']);return$x;}
function setting(string $key,$default=''){static $cache=[];if(array_key_exists($key,$cache))return$cache[$key];$s=db()->prepare('SELECT setting_value FROM settings WHERE setting_key=? LIMIT 1');$s->execute([$key]);return$cache[$key]=$s->fetchColumn()??$default;}
function current_admin():?array{if(empty($_SESSION['admin_id']))return null;$s=db()->prepare('SELECT * FROM users WHERE id=? AND is_admin=1 LIMIT 1');$s->execute([(int)$_SESSION['admin_id']]);return$s->fetch()?:null;}
function require_admin():array{$a=current_admin();if(!$a||$a['status']!=='ACTIVE')go('login.php');return$a;}
function log_activity(string $action,?int $actor=null,array $meta=[]):void{try{db()->prepare('INSERT INTO activity_logs(action,actor_id,meta_json,ip,created_at) VALUES(?,?,?,?,NOW())')->execute([$action,$actor,json_encode($meta),$_SERVER['REMOTE_ADDR']??'']);}catch(Throwable $e){error_log($e->getMessage());}}
function json_out(array $d,int $s=200):never{http_response_code($s);header('Content-Type: application/json; charset=utf-8');echo json_encode($d,JSON_UNESCAPED_SLASHES);exit;}
function api_finish(array $d,int $s=200):never{try{db()->prepare('INSERT INTO api_logs(route,method,ip,status,created_at) VALUES(?,?,?,?,NOW())')->execute([trim(parse_url($_SERVER['REQUEST_URI']??'',PHP_URL_PATH),'/'),$_SERVER['REQUEST_METHOD']??'GET',$_SERVER['REMOTE_ADDR']??'',$s]);}catch(Throwable $e){error_log($e->getMessage());}json_out($d,$s);}
function bearer():string{$h=$_SERVER['HTTP_AUTHORIZATION']??'';return preg_match('/Bearer\s+(.+)/i',$h,$m)?trim($m[1]):'';} function api_key_ok():bool{$p=$_SERVER['HTTP_X_API_KEY']??'';return $p!==''&&API_SECRET!==''&&hash_equals(API_SECRET,$p);}
function api_user():?array{$t=bearer();if($t==='')return null;$s=db()->prepare('SELECT u.* FROM api_tokens a JOIN users u ON u.id=a.user_id WHERE a.token_hash=? AND a.expires_at>NOW() AND u.status="ACTIVE" LIMIT 1');$s->execute([hash('sha256',$t)]);return$s->fetch()?:null;}
function public_user(array $u):array{return['id'=>(int)$u['id'],'name'=>$u['name'],'username'=>$u['username'],'email'=>$u['email']??'','phone'=>$u['phone']??'','referral_code'=>$u['referral_code'],'referred_by'=>$u['referred_by']??null,'status'=>$u['status'],'created_at'=>$u['created_at']];}
function rate_limited(string $route):bool{$f=sys_get_temp_dir().'/eran_'.sha1(($_SERVER['REMOTE_ADDR']??'').$route.date('YmdHi'));$n=is_file($f)?(int)file_get_contents($f):0;if($n>=90)return true;file_put_contents($f,(string)($n+1),LOCK_EX);return false;}
