<?php
declare(strict_types=1);
require_once __DIR__ . '/../config/database.php';

use MongoDB\BSON\UTCDateTime;
use MongoDB\Collection;
use MongoDB\Operation\FindOneAndUpdate;

function e(mixed $value): string { return htmlspecialchars((string)$value, ENT_QUOTES, 'UTF-8'); }
function post(string $key, mixed $default = ''): mixed { return $_POST[$key] ?? $default; }
function redirect(string $url): never { header('Location: ' . $url); exit; }
function appUrl(string $path = ''): string { return APP_URL . ($path === '' ? '' : '/' . ltrim($path, '/')); }
function csrfToken(): string { if (empty($_SESSION['csrf_token'])) $_SESSION['csrf_token'] = bin2hex(random_bytes(32)); return $_SESSION['csrf_token']; }
function csrfField(): string { return '<input type="hidden" name="csrf_token" value="' . e(csrfToken()) . '">'; }
function verifyCsrf(?string $token): bool { return is_string($token) && !empty($_SESSION['csrf_token']) && hash_equals($_SESSION['csrf_token'], $token); }
function flash(string $type, string $message): void { $_SESSION['flash'][] = ['type'=>$type,'message'=>$message]; }
function consumeFlashes(): array { $messages = $_SESSION['flash'] ?? []; unset($_SESSION['flash']); return $messages; }
function formatCurrency(mixed $amount): string { return 'PKR ' . number_format((float)$amount, 2); }
function formatDate(mixed $date): string { if ($date instanceof UTCDateTime) $date=$date->toDateTime()->format('c'); return $date ? date('d M Y, h:i A', strtotime((string)$date)) : '—'; }
function nowIso(): string { return gmdate('c'); }
function docArray(mixed $doc): ?array { if (!$doc) return null; $row=json_decode(json_encode($doc),true); return is_array($row)?$row:null; }
function docsArray(iterable $docs): array { $result=[]; foreach($docs as $doc){$row=docArray($doc);if($row!==null)$result[]=$row;}return $result; }
function collection(string $name): Collection { return getDB()->selectCollection($name); }
function nextId(string $name): int { $row=docArray(collection('counters')->findOneAndUpdate(['_id'=>$name],['$inc'=>['value'=>1]],['upsert'=>true,'returnDocument'=>FindOneAndUpdate::RETURN_DOCUMENT_AFTER]));return (int)($row['value']??1); }
function getUserById(int $id): ?array { return docArray(collection('users')->findOne(['id'=>$id])); }
function getUserByIdentity(string $identity): ?array { return docArray(collection('users')->findOne(['$or'=>[['username'=>$identity],['email'=>$identity]]])); }
function getUserWallet(int $userId): array { return docArray(collection('wallets')->findOne(['user_id'=>$userId])) ?: ['user_id'=>$userId,'balance'=>0,'total_invested'=>0,'total_withdrawn'=>0,'profit_30_days'=>0,'commission'=>0,'last_earning_at'=>null]; }
function getSetting(string $key,mixed $default=null): mixed { $row=docArray(collection('settings')->findOne(['setting_key'=>$key]));return $row['setting_value']??$default; }
function setSetting(string $key,string $value): void { collection('settings')->updateOne(['setting_key'=>$key],['$set'=>['setting_key'=>$key,'setting_value'=>$value,'updated_at'=>nowIso()]],['upsert'=>true]); }
function getUserTransactions(int $userId,?string $type=null,int $limit=50): array { $filter=['user_id'=>$userId];if($type!==null)$filter['type']=$type;return docsArray(collection('transactions')->find($filter,['sort'=>['created_at'=>-1,'id'=>-1],'limit'=>max(1,min($limit,200))])); }
function addTransaction(int $userId,string $type,float $amount,string $description,?int $referenceId=null,string $status='completed'): int { $id=nextId('transactions');collection('transactions')->insertOne(['id'=>$id,'user_id'=>$userId,'type'=>$type,'amount'=>$amount,'description'=>$description,'reference_id'=>$referenceId,'status'=>$status,'created_at'=>nowIso()]);return $id; }
function getUserReferrals(int $userId,?int $level=null): array { $filter=['referrer_id'=>$userId];if($level!==null)$filter['level']=$level;$rows=docsArray(collection('referrals')->find($filter,['sort'=>['created_at'=>-1]]));foreach($rows as &$row){$user=getUserById((int)$row['referee_id']);if($user){$row['name']=$user['name'];$row['username']=$user['username'];$row['email']=$user['email'];$row['user_created_at']=$user['created_at']??null;}}return $rows; }
function getTeamStats(int $userId): array { $stats=['level1_count'=>0,'level2_count'=>0,'level3_count'=>0,'total_members'=>0,'total_volume'=>0.0,'total_commission'=>0.0];foreach([1,2,3] as $level)$stats['level'.$level.'_count']=(int)collection('referrals')->countDocuments(['referrer_id'=>$userId,'level'=>$level]);$stats['total_members']=$stats['level1_count']+$stats['level2_count']+$stats['level3_count'];foreach(getUserReferrals($userId) as $row)$stats['total_volume']+=(float)getUserWallet((int)$row['referee_id'])['total_invested'];foreach(collection('commissions')->find(['user_id'=>$userId]) as $row)$stats['total_commission']+=(float)$row->amount;return $stats; }
function updateWalletBalance(int $userId,float $amount,string $operation='add'): bool { $filter=['user_id'=>$userId];$change=$operation==='subtract'?-abs($amount):abs($amount);if($operation==='subtract')$filter['balance']=['$gte'=>abs($amount)];return collection('wallets')->updateOne($filter,['$inc'=>['balance'=>$change],'$set'=>['updated_at'=>nowIso()]])->getModifiedCount()===1; }
function processReferral(int $newUserId,string $referralCode): void { $parent=docArray(collection('users')->findOne(['referral_code'=>$referralCode,'status'=>'active']));if(!$parent||((int)$parent['id']===$newUserId))return;$parentId=(int)$parent['id'];for($level=1;$level<=3&&$parentId>0;$level++){collection('referrals')->updateOne(['referrer_id'=>$parentId,'referee_id'=>$newUserId,'level'=>$level],['$setOnInsert'=>['id'=>nextId('referrals'),'referrer_id'=>$parentId,'referee_id'=>$newUserId,'level'=>$level,'created_at'=>nowIso()]],['upsert'=>true]);$parent=docArray(collection('users')->findOne(['id'=>$parentId]));$parentId=(int)($parent['referred_by']??0);}}
function addReferralCommissions(int $sourceUserId,float $amount): void { foreach(collection('referrals')->find(['referee_id'=>$sourceUserId],['sort'=>['level'=>1]]) as $ref){$level=(int)$ref->level;$commission=round($amount*(float)getSetting('level'.$level.'_commission',0)/100,2);if($commission<=0)continue;$referrer=(int)$ref->referrer_id;collection('commissions')->insertOne(['id'=>nextId('commissions'),'user_id'=>$referrer,'source_user_id'=>$sourceUserId,'level'=>$level,'amount'=>$commission,'created_at'=>nowIso()]);collection('wallets')->updateOne(['user_id'=>$referrer],['$inc'=>['balance'=>$commission,'commission'=>$commission],'$set'=>['updated_at'=>nowIso()]]);addTransaction($referrer,'commission',$commission,'Level '.$level.' referral commission',null,'completed');}}
function activePackages(): array { return docsArray(collection('packages')->find(['status'=>'active'],['sort'=>['price'=>1]])); }
function createInvestment(int $userId,int $packageId): array { $package=docArray(collection('packages')->findOne(['id'=>$packageId,'status'=>'active']));if(!$package)return ['success'=>false,'message'=>'Selected package is not available.'];$amount=(float)$package['price'];if(!updateWalletBalance($userId,$amount,'subtract'))return ['success'=>false,'message'=>'Insufficient wallet balance.'];$id=nextId('investments');$started=nowIso();$ends=date('c',strtotime('+'.(int)$package['validity_days'].' days'));collection('wallets')->updateOne(['user_id'=>$userId],['$inc'=>['total_invested'=>$amount],'$set'=>['updated_at'=>nowIso()]]);collection('investments')->insertOne(['id'=>$id,'user_id'=>$userId,'package_id'=>$packageId,'amount'=>$amount,'daily_profit'=>(float)$package['daily_profit'],'validity_days'=>(int)$package['validity_days'],'status'=>'active','started_at'=>$started,'ends_at'=>$ends,'created_at'=>$started]);addTransaction($userId,'investment',$amount,'Purchased '.$package['name'],$id,'completed');addReferralCommissions($userId,$amount);return ['success'=>true,'message'=>'Package purchased successfully.']; }
function collectDailyEarning(int $userId): array { $current=nowIso();$earning=0.0;foreach(collection('investments')->find(['user_id'=>$userId,'status'=>'active']) as $investment){if((string)$investment->started_at<=$current&&(string)$investment->ends_at>=$current)$earning+=(float)$investment->daily_profit;}if($earning<=0)return ['success'=>false,'message'=>'No active package earning is available.'];$wallet=getUserWallet($userId);if(!empty($wallet['last_earning_at'])&&strtotime((string)$wallet['last_earning_at'])>strtotime('-20 hours'))return ['success'=>false,'message'=>'Earning has already been collected recently.'];collection('wallets')->updateOne(['user_id'=>$userId],['$inc'=>['balance'=>$earning,'profit_30_days'=>$earning],'$set'=>['last_earning_at'=>$current,'updated_at'=>$current]]);addTransaction($userId,'reward',$earning,'Daily package earning',null,'completed');return ['success'=>true,'amount'=>$earning,'message'=>'Earning collected successfully.'];}
function userDeposits(int $userId): array { return docsArray(collection('deposits')->find(['user_id'=>$userId],['sort'=>['created_at'=>-1]])); }
function userWithdrawals(int $userId): array { return docsArray(collection('withdrawals')->find(['user_id'=>$userId],['sort'=>['created_at'=>-1]])); }
function userInvestments(int $userId): array { $rows=docsArray(collection('investments')->find(['user_id'=>$userId],['sort'=>['created_at'=>-1]]));foreach($rows as &$row){$p=docArray(collection('packages')->findOne(['id'=>(int)$row['package_id']]));$row['name']=$p['name']??'Package';}return $rows; }
function pendingTotals(int $userId): array { $result=['deposit'=>0.0,'withdrawal'=>0.0];foreach(['deposit','withdrawal'] as $type){$name=$type==='deposit'?'deposits':'withdrawals';foreach(collection($name)->find(['user_id'=>$userId,'status'=>'pending']) as $row)$result[$type]+=(float)$row->amount;}return $result; }
function adminUsers(): array { $rows=docsArray(collection('users')->find([],['sort'=>['created_at'=>-1]]));foreach($rows as &$row){$w=getUserWallet((int)$row['id']);$row['balance']=$w['balance'];$row['total_invested']=$w['total_invested'];}return $rows; }
function adminTransactions(int $limit=10): array { $rows=docsArray(collection('transactions')->find([],['sort'=>['created_at'=>-1,'id'=>-1],'limit'=>$limit]));foreach($rows as &$row){$u=getUserById((int)$row['user_id']);$row['username']=$u['username']??'Unknown';}return $rows; }
function adminDeposits(): array { $rows=docsArray(collection('deposits')->find([],['sort'=>['created_at'=>-1]]));foreach($rows as &$row){$u=getUserById((int)$row['user_id']);$row['username']=$u['username']??'Unknown';}return $rows; }
function adminWithdrawals(): array { $rows=docsArray(collection('withdrawals')->find([],['sort'=>['created_at'=>-1]]));foreach($rows as &$row){$u=getUserById((int)$row['user_id']);$row['username']=$u['username']??'Unknown';}return $rows; }
function adminReferrals(): array { $rows=docsArray(collection('referrals')->find([],['sort'=>['created_at'=>-1]]));foreach($rows as &$row){$a=getUserById((int)$row['referrer_id']);$b=getUserById((int)$row['referee_id']);$row['referrer']=$a['username']??'Unknown';$row['referee']=$b['username']??'Unknown';}return $rows; }
function adminCounts(): array { return ['users'=>(int)collection('users')->countDocuments([]),'deposits'=>(int)collection('deposits')->countDocuments([]),'withdrawals'=>(int)collection('withdrawals')->countDocuments([]),'packages'=>(int)collection('packages')->countDocuments([]),'pending_deposits'=>(int)collection('deposits')->countDocuments(['status'=>'pending']),'pending_withdrawals'=>(int)collection('withdrawals')->countDocuments(['status'=>'pending'])]; }
