<?php
declare(strict_types=1);require_once __DIR__.'/../includes/functions.php';
$route=trim(parse_url($_SERVER['REQUEST_URI']??'',PHP_URL_PATH),'/');$route=preg_replace('#^(?:admin/)?api/?#','',$route);$method=$_SERVER['REQUEST_METHOD']??'GET';
if($method==='OPTIONS'){header('Access-Control-Allow-Origin: '.PUBLIC_PANEL_ORIGIN);header('Access-Control-Allow-Headers: Content-Type, Authorization, X-API-Key');header('Access-Control-Allow-Methods: GET, POST, OPTIONS');exit;}if(($_SERVER['HTTP_ORIGIN']??'')===PUBLIC_PANEL_ORIGIN)header('Access-Control-Allow-Origin: '.PUBLIC_PANEL_ORIGIN);header('Vary: Origin');if(rate_limited($route))api_finish(['ok'=>false,'error'=>'Rate limit exceeded.'],429);if(!api_key_ok())api_finish(['ok'=>false,'error'=>'Invalid API key.'],401);
$body=json_decode(file_get_contents('php://input'),true)?:[];if(!empty($_POST))$body=array_merge($body,$_POST);
if($route==='auth/register'&&$method==='POST'){$name=trim((string)($body['name']??''));$username=trim((string)($body['username']??''));$contact=trim((string)($body['contact']??''));$pass=(string)($body['password']??'');$ref=trim((string)($body['referral_code']??''));if($name===''||$username===''||$contact===''||strlen($pass)<8)api_finish(['ok'=>false,'error'=>'Invalid registration data.'],422);$q=db()->prepare('SELECT id FROM users WHERE username=? OR email=? OR phone=? LIMIT 1');$q->execute([$username,$contact,$contact]);if($q->fetch())api_finish(['ok'=>false,'error'=>'Account already exists.'],409);$r=null;if($ref){$s=db()->prepare('SELECT id FROM users WHERE referral_code=? AND status="ACTIVE" LIMIT 1');$s->execute([$ref]);$r=$s->fetchColumn()?:null;}$email=str_contains($contact,'@')?$contact:null;$phone=$email?null:$contact;db()->beginTransaction();try{$s=db()->prepare('INSERT INTO users(name,username,email,phone,password_hash,referral_code,referred_by,status,is_admin,created_at) VALUES(?,?,?,?,?,?,?,"ACTIVE",0,NOW())');$s->execute([$name,$username,$email,$phone,password_hash($pass,PASSWORD_DEFAULT),strtoupper(substr(bin2hex(random_bytes(5)),0,8)),$r]);$id=(int)db()->lastInsertId();db()->prepare('INSERT INTO wallets(user_id) VALUES(?)')->execute([$id]);if($r)db()->prepare('INSERT IGNORE INTO referrals(referrer_id,referee_id,level,created_at) VALUES(?,?,1,NOW())')->execute([$r,$id]);db()->commit();$u=db()->query('SELECT * FROM users WHERE id='.$id)->fetch();api_finish(['ok'=>true,'data'=>['user'=>public_user($u)]],201);}catch(Throwable $e){db()->rollBack();api_finish(['ok'=>false,'error'=>'Registration failed.'],500);}}
if($route==='auth/login'&&$method==='POST'){$login=trim((string)($body['login']??''));$pass=(string)($body['password']??'');$s=db()->prepare('SELECT * FROM users WHERE (username=? OR email=? OR phone=?) AND is_admin=0 LIMIT 1');$s->execute([$login,$login,$login]);$u=$s->fetch();if(!$u||$u['status']!=='ACTIVE'||!password_verify($pass,$u['password_hash']))api_finish(['ok'=>false,'error'=>'Invalid credentials.'],401);$token=bin2hex(random_bytes(32));db()->prepare('INSERT INTO api_tokens(token_hash,user_id,expires_at,created_at) VALUES(?,?,DATE_ADD(NOW(),INTERVAL 1 DAY),NOW())')->execute([hash('sha256',$token),$u['id']]);api_finish(['ok'=>true,'data'=>['token'=>$token,'user'=>public_user($u)]]);}
if($route==='auth/logout'&&$method==='POST'){$t=bearer();if($t)db()->prepare('DELETE FROM api_tokens WHERE token_hash=?')->execute([hash('sha256',$t)]);api_finish(['ok'=>true,'data'=>['logged_out'=>true]]);}
$user=api_user();if(!$user)api_finish(['ok'=>false,'error'=>'Authentication required.'],401);
if($route==='auth/change-password'&&$method==='POST'){$cur=(string)($body['current_password']??'');$new=(string)($body['new_password']??'');if(strlen($new)<8||!password_verify($cur,$user['password_hash']))api_finish(['ok'=>false,'error'=>'Current password or new password is invalid.'],422);db()->prepare('UPDATE users SET password_hash=? WHERE id=?')->execute([password_hash($new,PASSWORD_DEFAULT),$user['id']]);log_activity('Public password changed',(int)$user['id']);api_finish(['ok'=>true,'data'=>['updated'=>true]]);}
if($route==='users/me'&&$method==='GET'){$s=db()->prepare('SELECT balance,total_invested,total_withdrawn,profit_30_days,commission FROM wallets WHERE user_id=?');$s->execute([$user['id']]);api_finish(['ok'=>true,'data'=>['user'=>public_user($user),'wallet'=>$s->fetch()?:[]]]);}
if($route==='settings/public'&&$method==='GET'){$s=db()->query('SELECT setting_key,setting_value FROM settings WHERE is_public=1');$out=[];foreach($s as $r)$out[$r['setting_key']]=$r['setting_value'];api_finish(['ok'=>true,'data'=>['settings'=>$out,'referral_levels'=>['l1'=>(float)($out['commission_l1']??11),'l2'=>(float)($out['commission_l2']??3),'l3'=>(float)($out['commission_l3']??2)]]]);}
if($route==='payment-methods'&&$method==='GET'){$items=db()->query("SELECT id,name,account_name,account_number FROM payment_methods WHERE status='ACTIVE' ORDER BY display_order,id")->fetchAll();api_finish(['ok'=>true,'data'=>['payment_methods'=>$items]]);}
if($route==='packages'&&$method==='GET'){$items=db()->query("SELECT id,name,description,price,validity_days,daily_profit,total_return,status FROM packages WHERE status='ACTIVE' ORDER BY id DESC")->fetchAll();api_finish(['ok'=>true,'data'=>['packages'=>$items]]);}
if($route==='demo-transactions'&&$method==='GET'){$s=db()->prepare('SELECT id,type,amount,payment_method,transaction_id,status,created_at FROM demo_transactions WHERE user_id=? ORDER BY created_at DESC');$s->execute([$user['id']]);$items=$s->fetchAll();api_finish(['ok'=>true,'data'=>['transactions'=>$items]]);}
if($route==='demo-transactions'&&$method==='POST'){$type=in_array(($body['type']??''),['DEPOSIT','WITHDRAWAL','PACKAGE'],true)?$body['type']:'';$amount=(float)($body['amount']??0);if($type===''||$amount<=0)api_finish(['ok'=>false,'error'=>'Invalid simulated transaction.'],422);if($type==='WITHDRAWAL'){$s=db()->prepare('SELECT balance FROM wallets WHERE user_id=?');$s->execute([$user['id']]);if($amount>(float)$s->fetchColumn())api_finish(['ok'=>false,'error'=>'Amount exceeds available balance.'],422);}$file=$_FILES['proof_image']??null;$proof=null;if($file&&$file['error']===UPLOAD_ERR_OK){if($file['size']>3*1024*1024)api_finish(['ok'=>false,'error'=>'File too large.'],422);$mime=(new finfo(FILEINFO_MIME_TYPE))->file($file['tmp_name']);if(!in_array($mime,['image/jpeg','image/png','image/webp'],true))api_finish(['ok'=>false,'error'=>'Invalid upload type.'],422);if(!is_dir(UPLOAD_DIR))mkdir(UPLOAD_DIR,0750,true);$proof=bin2hex(random_bytes(16)).'.'.(str_contains($mime,'png')?'png':(str_contains($mime,'webp')?'webp':'jpg'));move_uploaded_file($file['tmp_name'],UPLOAD_DIR.'/'.$proof);db()->prepare('INSERT INTO uploads(user_id,stored_name,mime,size,created_at) VALUES(?,?,?,?,NOW())')->execute([$user['id'],$proof,$mime,$file['size']]);}$tx=trim((string)($body['transaction_id']??('ERAN-'.strtoupper(bin2hex(random_bytes(4))))));db()->prepare('INSERT INTO demo_transactions(user_id,type,amount,payment_method,transaction_id,account_details,proof_file,status,created_at) VALUES(?,?,?,?,?,?,?,"PENDING",NOW())')->execute([$user['id'],$type,$amount,trim((string)($body['payment_method']??'ERAN+ WALLET')),$tx,trim((string)($body['account_details']??'')),$proof]);$id=(int)db()->lastInsertId();api_finish(['ok'=>true,'data'=>['transaction'=>['id'=>$id,'status'=>'PENDING']]],201);}
if($route==='team'&&$method==='GET'){$all=[];$front=[[(int)$user['id'],1]];while($front){[$parent,$level]=array_shift($front);if($level>3)break;$s=db()->prepare('SELECT id,name,username,status,created_at FROM users WHERE referred_by=? AND is_admin=0 ORDER BY created_at DESC');$s->execute([$parent]);foreach($s->fetchAll() as $m){$w=db()->prepare('SELECT total_invested FROM wallets WHERE user_id=?');$w->execute([$m['id']]);$m['level']=$level;$m['investment']=(float)($w->fetchColumn()?:0);$all[]=$m;$front[]=[$m['id'],$level+1];}}api_finish(['ok'=>true,'data'=>['members'=>$all]]);}
if($route==='activity'&&$method==='GET')api_finish(['ok'=>true,'data'=>['items'=>[]]]);api_finish(['ok'=>false,'error'=>'Endpoint not found.'],404);
